image: node:18

pipelines:
  default:
    - step:
        name: Install, Test & Build
        caches:
          - node
        script:
          - npm ci
          - npm test
          - npm run build
